services:
  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecoride
    restart: unless-stopped

  app:
    image: nancy13500/ecoride-app:latest
    container_name: ecoride_app
    volumes:
      - ./:/var/www/html
    environment:
      - DOCKER_ENV=1
      - DB_HOST=db
      - DB_NAME=ecoride
      - DB_USER=ecoride_user
      - DB_PASS=ecoride_pass
    depends_on:
      - db
    ports:
      - "8001:80"
    networks:
      - ecoride
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  ecoride:
    driver: bridge